<?php
/**
 * @file
 * Contains paypal_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function paypal_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the paypal_example module.
    case 'help.page.paypal_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Paypal example checkout') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function paypal_example_theme() {
  return [
    'paypal_example' => [
      'render element' => 'children',
      'template' => 'paypal-example',
      'variables' => [
        'data' => NULL,
      ]
    ]
  ];
}
